apiVersion: v1
kind: Service
metadata:
  name: my-node-app
spec:
  type: LoadBalancer
  selector:
    app: my-node-app
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  clusterIP: None
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
# apiVersion: v1
# kind: Service
# metadata:
#   name: mongo
#   labels:
#     app: mongo
# spec:
#   selector:
#     app: mongo
#   type: LoadBalancer

#   ports:
#     - protocol: TCP
#       port: 27020
#       targetPort: 27017
#       nodePort: 30010
